2023-03-18 22:55:45,348 - ERROR - csgo.py[:161] - 导出原始错误name 'df2' is not defined
2023-03-18 23:03:03,082 - ERROR - csgo.py[:53] - 网络异常可能是没有开VPN----HTTPSConnectionPool(host='www.etopfun.com', port=443): Max retries exceeded with url: /api/schema/bcitemlist.do?appid=730&mark_name=&rows=1000&page=1&quality=&rarity=&exterior=&lang=en (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000024D6B8140C8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2023-03-18 23:03:26,802 - ERROR - csgo.py[:53] - 网络异常可能是没有开VPN----HTTPSConnectionPool(host='www.etopfun.com', port=443): Max retries exceeded with url: /api/schema/bcitemlist.do?appid=730&mark_name=&rows=1000&page=1&quality=&rarity=&exterior=&lang=en (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000252D8824048>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
